/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage BottomBun;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::AssetImage Lettuce;
extern const Sifteo::AssetImage TopBun;
extern const Sifteo::AssetImage Ketchup;
extern const Sifteo::AssetImage Table;
extern const Sifteo::AssetImage Burger;
extern const Sifteo::AssetImage Cheese;
extern const Sifteo::AssetImage Bacon;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern const Sifteo::AssetAudio SFlip;
extern const Sifteo::AssetAudio SShake;
extern const Sifteo::AssetAudio SStop;
extern const Sifteo::AssetAudio STap;
